version: '2'
services:
    arg-app:
        image: arg
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://arg-postgresql:5432/arg
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8084:8084
    arg-postgresql:
        extends:
            file: postgresql.yml
            service: arg-postgresql
